### ISSUE TITLE
Error when i get data for index 

### ISSUE THREAD

**Issue by federicosanchez18** [zingimmick/laravel-scout-opensearch#56]
Hi !!

I have this error when i get info to index Benefits
 "message": "json_decode(): Argument #1 ($json) must be of type string, bool given",
    "exception": "TypeError",
    "file": "/var/www/html/vendor/zing/laravel-scout-opensearch/src/Engines/OpenSearchEngine.php",
    "line": 170,
    
 The instance to open search is in docker and this is running 
 
![image](https://github.com/zingimmick/laravel-scout-opensearch/assets/19497827/6165202f-e100-42ea-b444-c00a5fc6e0a3)

And the API Laravel comunicated with this container 
![image](https://github.com/zingimmick/laravel-scout-opensearch/assets/19497827/67a612ea-ca71-4dda-9de9-f4c8422973e3)

i configure the scout.php
![image](https://github.com/zingimmick/laravel-scout-opensearch/assets/19497827/e871b1d2-05a6-4f05-9d84-836345cf05d8)

and 
![image](https://github.com/zingimmick/laravel-scout-opensearch/assets/19497827/75b6f2f6-477d-4494-8ee4-9358061332a3)

Thanks

**Comment by zingimmick** [comment]
In fact, this project is for Alibaba Cloud OpenSearch Service, and the version for OpenSearch Project is still in test. See https://github.com/zingimmick/laravel-scout-opensearch/pull/57

I'm very sorry for the confusion caused by the project name, I'll consider renaming this project later to avoid ambiguity.
